exports.ACTION_HERO_TYPE_ATTACK_TURN = "AttackTurn";
exports.ACTION_HERO_TYPE_TAKE_DAMAGE = "TakeDamage";
exports.ACTION_HERO_TYPE_COUNTER_ATTACK = "CounterAttack";
exports.ACTION_HERO_TYPE_ACTIVE_SKILL_PASSIVE = "ActiveSkillPassive";
exports.ACTION_HERO_TYPE_USE_SKILL = "UseSkill";
exports.ACTION_HERO_TYPE = [
    exports.ACTION_HERO_TYPE_ATTACK_TURN,
    exports.ACTION_HERO_TYPE_TAKE_DAMAGE,
    exports.ACTION_HERO_TYPE_COUNTER_ATTACK,
    exports.ACTION_HERO_TYPE_ACTIVE_SKILL_PASSIVE,
    exports.ACTION_HERO_TYPE_USE_SKILL,
];