exports.ATTACK_TYPE_NONE = 0;
exports.ATTACK_TYPE_NORMAL = 1;
exports.ATTACK_TYPE_ATK_HIGHEST = 2;
exports.ATTACK_TYPE_HEALTH_LOWEST = 3;
exports.ATTACK_TYPE_HEALTH_HIGHEST = 4;
exports.ATTACK_TYPE_FORWARD = 5;
exports.ATTACK_TYPE_ALL_FRONT = 6;
exports.ATTACK_TYPE_ALL_MID = 7;
exports.ATTACK_TYPE_ALL_BACK = 8;
exports.ATTACK_TYPE_ALL = 9;
exports.ATTACK_TYPE_LINE_MOST_TARGET = 10;
exports.ATTACK_TYPE = [
    exports.ATTACK_TYPE_NONE,
    exports.ATTACK_TYPE_NORMAL,
    exports.ATTACK_TYPE_ATK_HIGHEST,
    exports.ATTACK_TYPE_HEALTH_LOWEST,
    exports.ATTACK_TYPE_HEALTH_HIGHEST,
    exports.ATTACK_TYPE_FORWARD,
    exports.ATTACK_TYPE_ALL_FRONT,
    exports.ATTACK_TYPE_ALL_MID,
    exports.ATTACK_TYPE_ALL_BACK,
    exports.ATTACK_TYPE_ALL,
    exports.ATTACK_TYPE_LINE_MOST_TARGET,
];