exports.DOT_TYPE_ATK = 0;
exports.DOT_TYPE_PERCENT_MAXHEALTH = 1;
exports.DOT_TYPE_PERCENT_CURHEALTH = 2;
exports.DOT_TYPE = [
    exports.DOT_TYPE_ATK,
    exports.DOT_TYPE_PERCENT_MAXHEALTH,
    exports.DOT_TYPE_PERCENT_CURHEALTH,
];