exports.SKILL_PRIORITY_AFFECT_HEALTH = 0;
exports.SKILL_PRIORITY_BUFF = 1;
exports.SKILL_PRIORITY_DEBUFF = 2;
exports.SKILL_PRIORITY_ACTION = 3;
exports.SKILL_PRIORITY = [
    exports.SKILL_PRIORITY_AFFECT_HEALTH,
    exports.SKILL_PRIORITY_BUFF,
    exports.SKILL_PRIORITY_DEBUFF,
    exports.SKILL_PRIORITY_ACTION,
];